src/main/kotlin/us/potatoboy/ledger/actions/AbstractActionType.kt, src/main/kotlin/us/potatoboy/ledger/commands/arguments/SearchParamArgument.kt, src/main/kotlin/us/potatoboy/ledger/listeners/BlockEventListener.kt
=> Add support for non-player actions with player sources

build.gradle
=> Shadow SQLite and exposed to allow for additional mod compat where the devs do not shadow these libraries

src/main/resources/data/ledger/lang/zh_cn.json
I removed the previous fork. MY BAD =-=
=> Re-edited and added Zh_cn translation

src/main/kotlin/us/potatoboy/ledger/actions/ActionType.kt, src/main/kotlin/us/potatoboy/ledger/database/DatabaseManager.kt
Fixes the action blacklist
Currently doesn't do anything because I forgot to re-add it in the database refactor
=> Fix blacklist

src/main/kotlin/com/github/quiltservertools/ledger/commands/subcommands/PreviewCommand.kt
=> Cancel current preview before applying a new one

src/main/java/com/github/quiltservertools/ledger/mixin/callbacks/ServerPlayInteractionManagerMixin.java, src/main/kotlin/com/github/quiltservertools/ledger/callbacks/PlayerBlockAttackCallback.kt, src/main/kotlin/com/github/quiltservertools/ledger/listeners/PlayerEventListener.kt, src/main/resources/ledger.mixins.json
=> Implement custom attack block callback

src/main/kotlin/com/github/quiltservertools/ledger/actions/BlockBreakActionType.kt, src/main/kotlin/com/github/quiltservertools/ledger/actions/BlockChangeActionType.kt
=> Fix nbt rollback reading

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/build.yml, build.gradle
Changed gradle version to include action build or current commit
=> Added issue templates

src/main/kotlin/com/github/quiltservertools/ledger/database/DatabaseManager.kt
=> Fix AND statement grouping in database selections

src/main/kotlin/com/github/quiltservertools/ledger/utility/MessageUtils.kt
Loops dependig on which page you are and how much pages are in total
=> fix sending network results

src/main/kotlin/com/github/quiltservertools/ledger/actionutils/ActionFactory.kt, src/main/kotlin/com/github/quiltservertools/ledger/listeners/BlockEventListener.kt, src/main/kotlin/com/github/quiltservertools/ledger/listeners/PlayerEventListener.kt, src/main/kotlin/com/github/quiltservertools/ledger/utility/InspectionManager.kt
=> Fix player casts

src/main/java/com/github/quiltservertools/ledger/mixin/FlintAndSteelItemMixin.java, src/main/resources/ledger.mixins.json
=> Log flint and steel usage

src/main/java/com/github/quiltservertools/ledger/mixin/callbacks/ItemScattererMixin.java, src/main/java/com/github/quiltservertools/ledger/mixin/callbacks/SlotMixin.java, src/main/kotlin/com/github/quiltservertools/ledger/actions/AbstractActionType.kt, src/main/kotlin/com/github/quiltservertools/ledger/actionutils/ActionFactory.kt, src/main/kotlin/com/github/quiltservertools/ledger/listeners/BlockEventListener.kt, src/main/kotlin/com/github/quiltservertools/ledger/utility/Sources.kt
=> Add source constants

.github/workflows/release.yml, build.gradle.kts
Automated publishing to curseforge and modrinth on release.
=> Gradle publish

build.gradle.kts, gradle.properties, libs.versions.toml
=> Bump version

src/main/kotlin/com/github/quiltservertools/ledger/actions/AbstractActionType.kt, src/main/kotlin/com/github/quiltservertools/ledger/commands/arguments/SearchParamArgument.kt
=> Changed `range` parameter to auto-set the current world

docs/extensions/extensions.md, docs/install.md, docs/parameters.md, docs/translations.md, mkdocs.yml
Add translations.md
Change `time` parameter docs
=> Add more documentation to `ledger-databases` extension

src/main/kotlin/com/github/quiltservertools/ledger/database/DatabaseManager.kt, src/main/resources/fabric.mod.json
=> Change exposed transaction to use specific database, not global state

src/main/kotlin/com/github/quiltservertools/ledger/Ledger.kt, src/main/kotlin/com/github/quiltservertools/ledger/listeners/WorldEventListener.kt
Fixes support for runtime worlds
=> Add worlds to world table when instead of just at startup

detekt.yml, docs/commands/player.md, mkdocs.yml, src/main/kotlin/com/github/quiltservertools/ledger/actions/AbstractActionType.kt, src/main/kotlin/com/github/quiltservertools/ledger/commands/LedgerCommand.kt, src/main/kotlin/com/github/quiltservertools/ledger/commands/subcommands/PlayerCommand.kt, src/main/kotlin/com/github/quiltservertools/ledger/database/DatabaseManager.kt, src/main/kotlin/com/github/quiltservertools/ledger/utility/MessageUtils.kt, src/main/kotlin/com/github/quiltservertools/ledger/utility/PlayerResult.kt, src/main/resources/data/ledger/lang/en_us.json
This adds `/ledger player <profile>`, which can be used to lookup the logged information of a player (first and last join time)
Closes #92
=> Add player command

src/main/kotlin/com/github/quiltservertools/ledger/database/DatabaseManager.kt
=> Don't use database while autosave is disabled

src/main/kotlin/com/github/quiltservertools/ledger/commands/subcommands/RestoreCommand.kt, src/main/kotlin/com/github/quiltservertools/ledger/database/DatabaseManager.kt
done in a separate PR from #119
=> Restore Command, make actions are looped in reverse order

build.gradle.kts, libs.versions.toml, src/main/java/com/github/quiltservertools/ledger/mixin/FallingBlockEntityMixin.java, src/main/kotlin/com/github/quiltservertools/ledger/Ledger.kt, src/main/kotlin/com/github/quiltservertools/ledger/config/DatabaseSpec.kt, src/main/kotlin/com/github/quiltservertools/ledger/database/DatabaseManager.kt, src/main/resources/fabric.mod.json, src/main/resources/ledger.toml
=> Add automatic purging from config

src/main/java/com/github/quiltservertools/ledger/mixin/BlockMixin.java
=> Fix supported blocks losing nbt when rolled back

src/main/java/com/github/quiltservertools/ledger/mixin/ExplosionMixin.java
=> Attach player sources to creeper explosions

src/main/kotlin/com/github/quiltservertools/ledger/actionutils/ActionSearchParams.kt, src/main/kotlin/com/github/quiltservertools/ledger/commands/arguments/SearchParamArgument.kt, src/main/kotlin/com/github/quiltservertools/ledger/database/DatabaseManager.kt, src/main/kotlin/com/github/quiltservertools/ledger/utility/InspectionManager.kt
Refactor action search param to use BlockBox
=> Inspect both sides of chest when inspecting a double chest

src/main/java/com/github/quiltservertools/ledger/mixin/blocks/SpongeBlockMixin.java
=> Fix crash with sponge placement

docs/networking.md
Blaming Yitzy for not documenting this
=> Fix network documentation

src/main/kotlin/com/github/quiltservertools/ledger/commands/parameters/SourceParameter.kt
=> Remove source search restrictions

build.gradle.kts, libs.versions.toml
=> Remove serverOnlyMinecraftJar() from build.gradle.kts until fixed

src/main/kotlin/com/github/quiltservertools/ledger/Ledger.kt, src/main/kotlin/com/github/quiltservertools/ledger/database/DatabaseManager.kt
Catch exception when executing actions, to prevent `collect` from returning.
Fixes #185
=> Fix Ledger failing to commit any transactions, if one throws an exception.

build.gradle.kts, gradle.properties
=> Bump version to 1.2.8

.github/workflows/release.yml, build.gradle.kts, gradle.properties, src/main/resources/fabric.mod.json
Releases should now auto deploy to curseforge and modrinth.
Pulls changelog from Github release body
Need to check env variables
=> Migrate release action to Kir-Antipov/mc-publish

build.gradle.kts
=> Fix metadata stripping

.github/workflows/release.yml
Github deprecated the old verisons. Pain
=> Bump release action version

docs/parameters.md, src/main/kotlin/com/github/quiltservertools/ledger/commands/arguments/SearchParamArgument.kt, src/main/kotlin/com/github/quiltservertools/ledger/commands/parameters/SourceParameter.kt, src/main/kotlin/com/github/quiltservertools/ledger/database/DatabaseManager.kt
Switched sqlite to use WAL journaling for concurrent read and writes
Added automatic query retry for rare cases of concurrent writes (rollback at the same time as heavy inserts)
Improve handling of invalid arguments
=> Remove mutex from default sqlite

src/main/resources/data/ledger/lang/es_es.json
Texts translated into Spanish :)
=> Spanish translation for Ledger

src/main/java/com/github/quiltservertools/ledger/mixin/ChestBlockMixin.java, src/main/kotlin/com/github/quiltservertools/ledger/utility/InspectionManager.kt, src/main/resources/ledger.mixins.json
This bug was introduced in #304 
The double chest code is special ... and needs special treatment
=> Fix double chest logging
